package jserver;

public enum TrainerMode {
	SINGLE, MULTI, ALL_SYMBOLS, TRIANGLE, FRAME, ARROW, TREE, STAIRWAY, THM, ABC, 
	MODULO, DICE, STRIPES, X, Y, Z, SIZES, BACKGROUND, LETTERTREE, COORD, ABCOORD,
}